SueñoCelestePagos.Web/Areas/Administrador/Controllers/ClientesController.cs
using Ganss.Excel;
using PagedList;
using SueñoCelestePagos.Dal;
using SueñoCelestePagos.Web.Areas.Administrador.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SueñoCelestePagos.Web.Areas.Administrador.Controllers
{
    [AdministradorAuthorize]
    public class ClientesController : Controller
    {
        private SueñoCelestePagosContext db = new SueñoCelestePagosContext();

        // GET: Administrador/Clientes
        public ActionResult Index(int page = 1)
        {
            var Clientes = db.Clientes.Include(t => t.Localidad).ToList();

            return View(Clientes.ToPagedList(page,15));
        }

        public FileContentResult ClientesConPagos()
        {
            DateTime hoy = DateTime.Today;

            var pagosRealizados = db.PagosCartonesVendidos.Include(t => t.CartonVendido).Include(t => t.CartonVendido.Carton).Where(x => x.Pagado && x.CartonVendido.Carton.Año == hoy.Year).ToList();

            var CartonesId = pagosRealizados.Select(x => x.CartonVendidoID).ToList().Distinct();

            var ClientesId = db.CartonesVendidos.Where(x => CartonesId.Contains(x.ID)).Select(x => x.ClienteID).Distinct();

            //var clientes = db.Clientes.Where(x => ClientesId.Contains(x.ID)).ToList();

            var clientes = (from oClientes in db.Clientes
                            join oCartonComprado in db.CartonesVendidos on oClientes.ID equals oCartonComprado.ClienteID
                            join oCarton in db.Cartones on oCartonComprado.CartonID equals oCarton.ID
                            join oLocalidad in db.Localidades on oClientes.LocalidadID equals oLocalidad.ID
                            join oProvincia in db.Provicias on oLocalidad.ProvinciaID equals oProvincia.ID
                            where ClientesId.Contains(oClientes.ID)
                            select new
                            {
                                NroCarton = oCarton.Numero,
                                Nombre = oClientes.Nombre,
                                Apellido = oClientes.Apellido,
                                Dni = oClientes.Dni,
                                AreaCelular = oClientes.AreaCelular,
                                NumeroCelular = oClientes.NumeroCelular,
                                Email = oClientes.Email,
                                FechaNacimiento = oClientes.FechaNacimiento,
                                Sexo = oClientes.Sexo,
                                CalleDomicilio = oClientes.Calle,
                                AlturaDomicilio = oClientes.Altura,
                                Localidad = oLocalidad.Nombre,
                                CodPostal = oLocalidad.CodPostal,
                                Provincia = oProvincia.Nombre
                            }).ToList();

            ExcelMapper mapper = new ExcelMapper();

            var newFile = Server.MapPath("~/Archivos/Exportacion/Clientes/clientes" + hoy.Day + hoy.Month + hoy.Year + ".xlsx");

            mapper.Save(newFile, clientes, "SheetName", true);

            String mimeType = MimeMapping.GetMimeMapping(newFile);

            byte[] stream = System.IO.File.ReadAllBytes(newFile);

            /*
             String file = Server.MapPath("~/ParentDir/ChildDir" + fileName);
             String mimeType = MimeMapping.GetMimeMapping(path);

             byte[] stream = System.IO.File.ReadAllBytes(file);
             */

            return File(stream, mimeType);
        }
    }
}

SueñoCelestePagos.Web/Areas/Administrador/Controllers/FechasDeVencimientosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PagedList;
using SueñoCelestePagos.Dal;
using SueñoCelestePagos.Entities;
using SueñoCelestePagos.Web.Areas.Administrador.Models;

namespace SueñoCelestePagos.Web.Areas.Administrador.Controllers
{
    [AdministradorAuthorize]
    public class FechasDeVencimientosController : Controller
    {
        private SueñoCelestePagosContext db = new SueñoCelestePagosContext();

        // GET: ContentAdmin/FechasDeVencimientos
        public ActionResult Index(int? page)
        {
            var fechasDeVencimiento = db.FechasDeVencimiento.ToList();

            if (page == null)
            {
                page = 1;
            }

            return View(fechasDeVencimiento.ToPagedList(page.Value, 10));
        }

        // GET: ContentAdmin/FechasDeVencimientos/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FechaDeVencimiento fechaDeVencimiento = db.FechasDeVencimiento.Find(id);
            if (fechaDeVencimiento == null)
            {
                return HttpNotFound();
            }
            return View(fechaDeVencimiento);
        }

        // GET: ContentAdmin/FechasDeVencimientos/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ContentAdmin/FechasDeVencimientos/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Mes,Año,PrimerVencimiento,SegundoVencimiento")] FechaDeVencimiento fechaDeVencimiento)
        {
            if (ModelState.IsValid)
            {
                db.FechasDeVencimiento.Add(fechaDeVencimiento);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(fechaDeVencimiento);
        }

        // GET: ContentAdmin/FechasDeVencimientos/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FechaDeVencimiento fechaDeVencimiento = db.FechasDeVencimiento.Find(id);
            if (fechaDeVencimiento == null)
            {
                return HttpNotFound();
            }
            return View(fechaDeVencimiento);
        }

        // POST: ContentAdmin/FechasDeVencimientos/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Mes,Año,PrimerVencimiento,SegundoVencimiento")] FechaDeVencimiento fechaDeVencimiento)
        {
            if (ModelState.IsValid)
            {
                db.Entry(fechaDeVencimiento).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(fechaDeVencimiento);
        }

        // GET: ContentAdmin/FechasDeVencimientos/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FechaDeVencimiento fechaDeVencimiento = db.FechasDeVencimiento.Find(id);
            if (fechaDeVencimiento == null)
            {
                return HttpNotFound();
            }
            return View(fechaDeVencimiento);
        }

        // POST: ContentAdmin/FechasDeVencimientos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            FechaDeVencimiento fechaDeVencimiento = db.FechasDeVencimiento.Find(id);
            db.FechasDeVencimiento.Remove(fechaDeVencimiento);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SueñoCelestePagos.Web/Areas/Administrador/Controllers/HomeController.cs
using SueñoCelestePagos.Web.Areas.Administrador.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SueñoCelestePagos.Web.Areas.Administrador.Controllers
{
    [AdministradorAuthorize]
    public class HomeController : Controller
    {
        // GET: Administrador/Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

SueñoCelestePagos.Web/Areas/Administrador/Controllers/InstitucionesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SueñoCelestePagos.Dal;
using SueñoCelestePagos.Entities;

namespace SueñoCelestePagos.Web.Areas.Administrador.Controllers
{
    public class InstitucionesController : Controller
    {
        private SueñoCelestePagosContext db = new SueñoCelestePagosContext();

        // GET: Administrador/Instituciones
        public ActionResult Index()
        {
            return View(db.Instituciones.ToList());
        }

        // GET: Administrador/Instituciones/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Institucion institucion = db.Instituciones.Find(id);
            if (institucion == null)
            {
                return HttpNotFound();
            }
            return View(institucion);
        }

        // GET: Administrador/Instituciones/Create
        public ActionResult Create()
        {
            ViewBag.LocalidadID = new SelectList(db.Localidades, "ID", "Descripcion");

            return View();
        }

        // POST: Administrador/Instituciones/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Nombre,Cuit,Calle,Altura,LocalidadID,AreaTelefono,NumeroTelefono")] Institucion institucion)
        {
            if (ModelState.IsValid)
            {
                db.Instituciones.Add(institucion);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.LocalidadID = new SelectList(db.Localidades, "ID", "Descripcion", institucion.LocalidadID);

            return View(institucion);
        }

        // GET: Administrador/Instituciones/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Institucion institucion = db.Instituciones.Find(id);
            if (institucion == null)
            {
                return HttpNotFound();
            }
            ViewBag.LocalidadID = new SelectList(db.Localidades, "ID", "Descripcion", institucion.LocalidadID);
            return View(institucion);
        }

        // POST: Administrador/Instituciones/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Nombre,Cuit,Calle,Altura,LocalidadID,AreaTelefono,NumeroTelefono")] Institucion institucion)
        {
            if (ModelState.IsValid)
            {
                db.Entry(institucion).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.LocalidadID = new SelectList(db.Localidades, "ID", "Descripcion", institucion.LocalidadID);
            return View(institucion);
        }

        public ActionResult Aporte(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Institucion institucion = db.Instituciones.Find(id);
            if (institucion == null)
            {
                return HttpNotFound();
            }
            ViewBag.LocalidadID = new SelectList(db.Localidades, "ID", "Descripcion");

            return View(institucion);
        }

        [HttpPost]
        public ActionResult Aporte(int? id, decimal Aporte, DateTime FechaAlta, DateTime? FechaBaja)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Institucion institucion = db.Instituciones.Find(id);
            if (institucion == null)
            {
                return HttpNotFound();
            }
            ViewBag.LocalidadID = new SelectList(db.Localidades, "ID", "Descripcion");

            if (Aporte < 1)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var AporteVigente = db.AporteInstitucion.Where(x => x.InstitucionID == id && x.FechaBaja != null).FirstOrDefault();
            if(AporteVigente == null)
            {
                AporteVigente = new AporteInstitucion();

                AporteVigente.InstitucionID = id.Value;
                AporteVigente.PorcAporte = Aporte;
                AporteVigente.FechaAlta = FechaAlta;
                AporteVigente.FechaBaja = FechaBaja;

                db.AporteInstitucion.Add(AporteVigente);
            }
            else
            {
                AporteVigente.FechaBaja = FechaAlta.AddDays(-1);

                AporteInstitucion NuevoAporte = new AporteInstitucion();

                NuevoAporte.InstitucionID = id.Value;
                NuevoAporte.PorcAporte = Aporte;
                NuevoAporte.FechaAlta = FechaAlta;
                NuevoAporte.FechaBaja = FechaBaja;

                db.AporteInstitucion.Add(NuevoAporte);
            }

            db.SaveChanges();

            return View();
        }

        // GET: Administrador/Instituciones/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Institucion institucion = db.Instituciones.Find(id);
            if (institucion == null)
            {
                return HttpNotFound();
            }
            return View(institucion);
        }

        // POST: Administrador/Instituciones/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Institucion institucion = db.Instituciones.Find(id);
            db.Instituciones.Remove(institucion);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SueñoCelestePagos.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SueñoCelestePagos.Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

SueñoCelestePagos.Web/Areas/Administrador/Views/Home/Index.cshtml
<!--BEGIN TITLE & BREADCRUMB PAGE-->

<h1 class="page-header">Home</h1>
<ul class="breadcrumb">
    <li><span class="glyphicon glyphicon-home">&nbsp;</span>Home</li>
    <li><a href="#">Home</a></li>
</ul>
<!--END TITLE & BREADCRUMB PAGE-->
<!--BEGIN CONTENT-->
<div class="page-content">
    <div id="tab-general">
        <div id="sum_box" class="row mbl">
            <div class="col-sm-6 col-md-3">
                <div class="panel profit db mbm">
                    <div class="panel-body">
                        @*<p class="icon">
                            <i class="icon fa fa-group"></i>
                        </p>*@
                        <h4 class="value">
                            <span data-counter="" data-start="10" data-end="50" data-step="1" data-duration="0"></span>
                            <a href="@Url.Action("Index","Compras")"><span>Compras</span></a>
                        </h4>
                        <p class="description">
                            Ingresar
                        </p>
                        <div class="progress progress-sm mbn">
                            <div role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 100%;" class="progress-bar progress-bar-info"></div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-sm-6 col-md-3">
                <div class="panel profit db mbm">
                    <div class="panel-body">
                        @*<p class="icon">
                            <i class="icon fa fa-group"></i>
                        </p>*@
                        <h4 class="value">
                            <span data-counter="" data-start="10" data-end="50" data-step="1" data-duration="0"></span>
                            <a href="@Url.Action("VentasACancelar","Compras")"><span>Cancelar Compras</span></a>
                        </h4>
                        <p class="description">
                            Ingresar
                        </p>
                        <div class="progress progress-sm mbn">
                            <div role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 100%;" class="progress-bar progress-bar-info"></div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-sm-6 col-md-3">
                <div class="panel profit db mbm">
                    <div class="panel-body">
                        @*<p class="icon">
                            <i class="icon fa fa-group"></i>
                        </p>*@
                        <h4 class="value">
                            <span data-counter="" data-start="10" data-end="50" data-step="1" data-duration="0"></span>
                            <a href="@Url.Action("Index","Clientes")"><span>Clientes</span></a>
                        </h4>
                        <p class="description">
                            Ingresar
                        </p>
                        <div class="progress progress-sm mbn">
                            <div role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 100%;" class="progress-bar progress-bar-info"></div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-sm-6 col-md-3">
                <div class="panel profit db mbm">
                    <div class="panel-body">
                        @*<p class="icon">
                            <i class="icon fa fa-group"></i>
                        </p>*@
                        <h4 class="value">
                            <span data-counter="" data-start="10" data-end="50" data-step="1" data-duration="0"></span>
                            <a href="@Url.Action("Index","FechasDeVencimientos")"><span>Fechas Vto</span></a>
                        </h4>
                        <p class="description">
                            Ingresar
                        </p>
                        <div class="progress progress-sm mbn">
                            <div role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 100%;" class="progress-bar progress-bar-info"></div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
        <hr />
        <div id="sum_box" class="row mbl">
            <div class="col-sm-6 col-md-3">
                <div class="panel profit db mbm">
                    <div class="panel-body">
                        @*<p class="icon">
                            <i class="icon fa fa-group"></i>
                        </p>*@
                        <h4 class="value">
                            <span data-counter="" data-start="10" data-end="50" data-step="1" data-duration="0"></span>
                            <a href="@Url.Action("Index","Instituciones")"><span>Instituciones</span></a>
                        </h4>
                        <p class="description">
                            Ingresar
                        </p>
                        <div class="progress progress-sm mbn">
                            <div role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 100%;" class="progress-bar progress-bar-green"></div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-sm-6 col-md-3">
                <div class="panel profit db mbm">
                    <div class="panel-body">
                        @*<p class="icon">
                            <i class="icon fa fa-group"></i>
                        </p>*@
                        <h4 class="value">
                            <span data-counter="" data-start="10" data-end="50" data-step="1" data-duration="0"></span>
                            <a href="@Url.Action("ResumenAcumulado","Compras")"><span>Panel de Compras Acumulado</span></a>
                        </h4>
                        <p class="description">
                            Ingresar
                        </p>
                        <div class="progress progress-sm mbn">
                            <div role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 100%;" class="progress-bar progress-bar-green"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!--END CONTENT-->