SueñoCelestePagos.Web/Areas/Administrador/Controllers/FechasLimitesDebitoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PagedList;
using SueñoCelestePagos.Dal;
using SueñoCelestePagos.Entities;

namespace SueñoCelestePagos.Web.Areas.Administrador.Controllers
{
    public class FechasLimitesDebitoController : Controller
    {
        private SueñoCelestePagosContext db = new SueñoCelestePagosContext();

        // GET: Administrador/FechasLimitesDebito
        public ActionResult Index(int? page)
        {
            var fechasLimite = db.FechasLimitesDebito.ToList();

            if (page == null)
            {
                page = 1;
            }

            return View(fechasLimite.ToPagedList(page.Value, 10));
        }

        // GET: Administrador/FechasLimitesDebito/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FechaLimiteDebito fechaLimiteDebito = db.FechasLimitesDebito.Find(id);
            if (fechaLimiteDebito == null)
            {
                return HttpNotFound();
            }
            return View(fechaLimiteDebito);
        }

        // GET: Administrador/FechasLimitesDebito/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Administrador/FechasLimitesDebito/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Mes,Año,FechaLimite")] FechaLimiteDebito fechaLimiteDebito)
        {
            if (ModelState.IsValid)
            {
                db.FechasLimitesDebito.Add(fechaLimiteDebito);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(fechaLimiteDebito);
        }

        // GET: Administrador/FechasLimitesDebito/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FechaLimiteDebito fechaLimiteDebito = db.FechasLimitesDebito.Find(id);
            if (fechaLimiteDebito == null)
            {
                return HttpNotFound();
            }
            return View(fechaLimiteDebito);
        }

        // POST: Administrador/FechasLimitesDebito/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Mes,Año,FechaLimite")] FechaLimiteDebito fechaLimiteDebito)
        {
            if (ModelState.IsValid)
            {
                db.Entry(fechaLimiteDebito).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(fechaLimiteDebito);
        }

        // GET: Administrador/FechasLimitesDebito/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FechaLimiteDebito fechaLimiteDebito = db.FechasLimitesDebito.Find(id);
            if (fechaLimiteDebito == null)
            {
                return HttpNotFound();
            }
            return View(fechaLimiteDebito);
        }

        // POST: Administrador/FechasLimitesDebito/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            FechaLimiteDebito fechaLimiteDebito = db.FechasLimitesDebito.Find(id);
            db.FechasLimitesDebito.Remove(fechaLimiteDebito);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SueñoCelestePagos.Web/Areas/Administrador/Views/FechasLimitesDebito/Create.cshtml
@model SueñoCelestePagos.Entities.FechaLimiteDebito

@{
    ViewBag.Title = "Nueva Fecha Limite";
}

<!--BEGIN TITLE & BREADCRUMB PAGE--><!--BEGIN TITLE & BREADCRUMB PAGE-->
<h1 class="page-header">Fechas Limite</h1>
<ul class="breadcrumb">
    <li><span class="glyphicon glyphicon-home">&nbsp;</span>Home</li>
    <li><a href="#">Fechas Limite</a></li>
</ul>
<!--END TITLE & BREADCRUMB PAGE-->

<hr />

<!--BEGIN CONTENT-->
<div class="page-content">
    <div id="tab-general">
        <div class="col-md-11">
            <div class="panel">
                <div class="panel-body">
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-horizontal">
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            <div class="form-group">
                                @Html.LabelFor(model => model.Mes, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Mes, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Mes, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Año, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Año, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Año, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.FechaLimite, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.FechaLimite, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.FechaLimite, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    <input type="submit" value="Create" class="btn btn-default" />
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-1">
                            </div>
                            <div class="col-md-2">
                                @Html.ActionLink("Volver", "Index", null, new { @class = "btn btn-primary" })
                            </div>
                            <div class="col-md-2">

                            </div>
                            <div class="col-md-2">

                            </div>
                            <div class="col-md-2">

                            </div>
                            <div class="col-md-2">
                                <input type="submit" value="Guardar" class="btn btn-primary" />
                            </div>
                        </div>
                    }

                </div>
            </div>
        </div>
    </div>
</div>

SueñoCelestePagos.Web/Areas/Administrador/Views/FechasLimitesDebito/Delete.cshtml
@model SueñoCelestePagos.Entities.FechaLimiteDebito

@{
    ViewBag.Title = "Eliminar Fecha Limite";
}

<!--BEGIN TITLE & BREADCRUMB PAGE--><!--BEGIN TITLE & BREADCRUMB PAGE-->
<h1 class="page-header">Fechas Limite</h1>
<ul class="breadcrumb">
    <li><span class="glyphicon glyphicon-home">&nbsp;</span>Home</li>
    <li><a href="#">Fechas Limite</a></li>
</ul>
<!--END TITLE & BREADCRUMB PAGE-->

<hr />

<!--BEGIN CONTENT-->
<div class="page-content">
    <div id="tab-general">
        <div class="col-md-11">
            <div class="panel">
                <div class="panel-body">
                    <h3>¿Estas seguro de querer Eliminar esta fecha?</h3>
                    <dl class="dl-horizontal">
                        <dt>
                            @Html.DisplayNameFor(model => model.Mes)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Mes)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Año)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Año)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.FechaLimite)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.FechaLimite)
                        </dd>
                    </dl>

                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-actions no-color">
                            <input type="submit" value="Eliminar" class="btn btn-default" /> |
                            @Html.ActionLink("Back to List", "Index")
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

SueñoCelestePagos.Web/Areas/Administrador/Views/FechasLimitesDebito/Details.cshtml
@model SueñoCelestePagos.Entities.FechaLimiteDebito

@{
    ViewBag.Title = "Details";
}

<!--BEGIN TITLE & BREADCRUMB PAGE--><!--BEGIN TITLE & BREADCRUMB PAGE-->
<h1 class="page-header">Fechas Limite</h1>
<ul class="breadcrumb">
    <li><span class="glyphicon glyphicon-home">&nbsp;</span>Home</li>
    <li><a href="#">Fechas Limite</a></li>
</ul>
<!--END TITLE & BREADCRUMB PAGE-->

<hr />

<!--BEGIN CONTENT-->
<div class="page-content">
    <div id="tab-general">
        <div class="col-md-11">
            <div class="panel">
                <div class="panel-body">
                    <div>
                        <dl class="dl-horizontal">
                            <dt>
                                @Html.DisplayNameFor(model => model.Mes)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.Mes)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.Año)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.Año)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.FechaLimite)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.FechaLimite)
                            </dd>

                        </dl>
                    </div>
                    <p>
                        @Html.ActionLink("Editar", "Edit", new { id = Model.ID }) |
                        @Html.ActionLink("Volver", "Index")
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>

SueñoCelestePagos.Web/Areas/Administrador/Views/FechasLimitesDebito/Edit.cshtml
@model SueñoCelestePagos.Entities.FechaLimiteDebito

@{
    ViewBag.Title = "Edit";
}

<!--BEGIN TITLE & BREADCRUMB PAGE--><!--BEGIN TITLE & BREADCRUMB PAGE-->
<h1 class="page-header">Fechas Limite</h1>
<ul class="breadcrumb">
    <li><span class="glyphicon glyphicon-home">&nbsp;</span>Home</li>
    <li><a href="#">Fechas Limite</a></li>
</ul>
<!--END TITLE & BREADCRUMB PAGE-->

<hr />

<!--BEGIN CONTENT-->
<div class="page-content">
    <div id="tab-general">
        <div class="col-md-11">
            <div class="panel">
                <div class="panel-body">
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()
                        <div class="form-horizontal">
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            @Html.HiddenFor(model => model.ID)

                            <div class="form-group">
                                @Html.LabelFor(model => model.Mes, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Mes, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Mes, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Año, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Año, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Año, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.FechaLimite, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.FechaLimite, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.FechaLimite, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    <input type="submit" value="Create" class="btn btn-default" />
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-1">
                            </div>
                            <div class="col-md-2">
                                @Html.ActionLink("Volver", "Index", null, new { @class = "btn btn-primary" })
                            </div>
                            <div class="col-md-2">

                            </div>
                            <div class="col-md-2">

                            </div>
                            <div class="col-md-2">

                            </div>
                            <div class="col-md-2">
                                <input type="submit" value="Guardar" class="btn btn-primary" />
                            </div>
                        </div>
                    }

                </div>
            </div>
        </div>
    </div>
</div>

SueñoCelestePagos.Web/Areas/Administrador/Views/FechasLimitesDebito/Index.cshtml
@model PagedList.IPagedList<SueñoCelestePagos.Entities.FechaLimiteDebito>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Index";
}

<!--BEGIN TITLE & BREADCRUMB PAGE--><!--BEGIN TITLE & BREADCRUMB PAGE-->
<h1 class="page-header">Fechas Limite</h1>
<ul class="breadcrumb">
    <li><span class="glyphicon glyphicon-home">&nbsp;</span>Home</li>
    <li><a href="#">Fechas Limite</a></li>
</ul>
<!--END TITLE & BREADCRUMB PAGE-->

<hr />

<div>
    <div class="col-md-8">
        @*@using (Html.BeginForm())
        {
            <div class="col-md-6">
                <input type="text" name="searchString" id="searchString" class="form-control" value="@ViewBag.CurrentFilter " />
            </div>
            <div class="col-md-2">
                <input type="submit" value="Buscar" class="btn btn-primary" />
            </div>
        }*@
    </div>
    <div class="col-md-4">
        <a href="@Url.Action("Create", "FechasLimitesDebito")" class="btn btn-primary">Agregar Nueva Fecha De Vencimiento</a>
    </div>
    <div class="clearfix">
    </div>
</div>

<hr />

<!--BEGIN CONTENT-->
<div class="page-content">
    <div id="tab-general">
        @if (Model.Count() > 0)
        {
            <table class="table">
                <tr>
                    <th>
                        @Html.DisplayName("Mes")
                    </th>
                    <th>
                        @Html.DisplayName("Año")
                    </th>
                    <th>
                        @Html.DisplayName("Fecha Limite")
                    </th>
                    <th></th>
                </tr>

                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Mes)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Año)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.FechaLimite)
                        </td>
                        <td>
                            @Html.ActionLink("Editar", "Edit", new { id = item.ID }) |
                            @Html.ActionLink("Detalles", "Details", new { id = item.ID }) |
                            @Html.ActionLink("Eliminar", "Delete", new { id = item.ID })
                        </td>
                    </tr>
                }

            </table>

            <div class="text-center">
                Pagina @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) de @Model.PageCount

                @Html.PagedListPager(Model, page => Url.Action("Index",
                    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))
            </div>
        }
        else
        {
            <div class="col-md-12">
                <div class="panel">
                    <div class="panel-heading">
                        <h3 class="text-center">Su Busqueda no dio Resultados</h3>
                    </div>
                </div>
            </div>
        }
    </div>
</div>
<!--END CONTENT-->
@*<p>
            @Html.ActionLink("Create New", "Create")
    </p>*@